version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "stock"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-6rkar9xf9ldp"
s3_prefix = "stock"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
